version: "3.6"
services:
    db:
        build: ./db
        command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=p4ssw0rd_1s_s0_h4rd_t0_gu3ss
            - MYSQL_DATABASE=basketball_store
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

    web:
        build: ./
        restart: unless-stopped 
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_ROOT_PASSWORD=p4ssw0rd_1s_s0_h4rd_t0_gu3ss
            - MYSQL_DATABASE=basketball_store
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password